# Generated by Django 2.1.7 on 2019-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=123)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
